# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ebc684e2d8bd2f36055b7965f9755822"
name = "my-custom-app"
handle = "my-custom-app-103"
application_url = "https://ddr-edgar-enhancement-alloy.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://ddr-edgar-enhancement-alloy.trycloudflare.com/auth/callback",
  "https://ddr-edgar-enhancement-alloy.trycloudflare.com/auth/shopify/callback",
  "https://ddr-edgar-enhancement-alloy.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false

[build]
dev_store_url = "eatwell-kitchen.myshopify.com"
automatically_update_urls_on_dev = true
